import { React, useEffect } from "react";
import { MDBContainer, MDBMask, MDBView } from "mdbreact";

import Title4PNG from "assets/bg-title4.png";

const Terms = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <MDBContainer fluid className="p-0">
      <MDBView>
        <img src={Title4PNG} className="img-fluid" alt="" />
        <MDBMask className="flex-center" overlay="black-light">
          <h1 className="font-weight-bold text-white">Terms & Conditions</h1>
        </MDBMask>
      </MDBView>
      <MDBContainer className="pb-5">
        <h3 className="py-5 text-center">Our Agreement & Terms</h3>
        <div className="d-md-flex">
          <div className="overflow-auto" style={{ maxHeight: "60vh" }}>
            <h4 className="text-center py-5">AGREEMENT TO TERMS</h4>
            <p>
              These Terms and Conditions constitute a legally binding agreement
              made between you, whether personally or on behalf of an entity
              (“you”) and [business entity name] (“we,” “us” or “our”),
              concerning your access to and use of the [website name.com]
              website as well as any other media form, media channel, mobile
              website or mobile application related, linked, or otherwise
              connected thereto (collectively, the “Site”).
            </p>
            <p>
              You agree that by accessing the Site, you have read, understood,
              and agree to be bound by all of these Terms and Conditions. If you
              do not agree with all of these Terms and Conditions, then you are
              expressly prohibited from using the Site and you must discontinue
              use immediately.
            </p>
            <p>
              Supplemental terms and conditions or documents that may be posted
              on the Site from time to time are hereby expressly incorporated
              herein by reference. We reserve the right, in our sole discretion,
              to make changes or modifications to these Terms and Conditions at
              any time and for any reason.
            </p>
            <p>
              We will alert you about any changes by updating the “Last updated”
              date of these Terms and Conditions, and you waive any right to
              receive specific notice of each such change.
            </p>
            <p>
              It is your responsibility to periodically review these Terms and
              Conditions to stay informed of updates. You will be subject to,
              and will be deemed to have been made aware of and to have
              accepted, the changes in any revised Terms and Conditions by your
              continued use of the Site after the date such revised Terms and
              Conditions are posted.
            </p>
            <p>
              The information provided on the Site is not intended for
              distribution to or use by any person or entity in any jurisdiction
              or country where such distribution or use would be contrary to law
              or regulation or which would subject us to any registration
              requirement within such jurisdiction or country.
            </p>
            <p>
              Accordingly, those persons who choose to access the Site from
              other locations do so on their own initiative and are solely
              responsible for compliance with local laws, if and to the extent
              local laws are applicable.
            </p>
            <p>
              These terms and conditions were generated by Termly’s Terms and
              Conditions Generator.
            </p>
            <p>
              Option 1: The Site is intended for users who are at least 18 years
              old. Persons under the age of 18 are not permitted to register for
              the Site.
            </p>
            <p>
              Option 2: [The Site is intended for users who are at least 13
              years of age.] All users who are minors in the jurisdiction in
              which they reside (generally under the age of 18) must have the
              permission of, and be directly supervised by, their parent or
              guardian to use the Site. If you are a minor, you must have your
              parent or guardian read and agree to these Terms and Conditions
              prior to you using the Site. INTELLECTUAL PROPERTY RIGHTS
            </p>
          </div>
        </div>
      </MDBContainer>
    </MDBContainer>
  );
};

export default Terms;
